---
- name: Setup SSH - Post Container Build/Rebuild
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    my_ssh_src: /app/.vscode/
    my_ssh_dir: /home/vscode/.ssh/
    my_id: vscode

  tasks:
    - name: Create the .ssh Directory
      file:
        path: "{{ my_ssh_dir }}"
        state: directory
        mode: "0700"
        owner: "{{my_id}}"
        group: "{{my_id}}"
    
    - name: Copy ssh files
      copy:
        src: "{{my_ssh_src}}/{{item.src}}"
        dest: "{{my_ssh_dir}}/{{item.tgt}}"
        owner: "{{my_id}}"
        group: "{{my_id}}"
        mode: "{{item.mode}}"
      loop:
        - { src: config, tgt: config, mode: "0600" }
        - { src: psmware, tgt: id_rsa, mode: "0600" }
        - { src: psmware.pub, tgt: id_rsa.pub, mode: "0644" }
        - { src: known_hosts, tgt: known_hosts, mode: "0644" }
    
    - name: Add Git User Email
      git_config:
        name: user.email
        scope: global
        state: present
        value: "{{ lookup('env', 'PSMWARE_GIT_EMAIL') }}"

    - name: Add Git User Name
      git_config:
        name: user.name
        scope: global
        state: present
        value: "{{ lookup('env', 'PSMWARE_GIT_NAME') }}"

    - name: Add Git User Signing Key
      git_config:
        name: user.signingkey
        scope: global
        state: present
        value: "{{ lookup('env', 'PSMWARE_GIT_KEY') }}"

    - name: Add Git Commit Sign
      git_config:
        name: commit.gpgsign
        scope: global
        state: present
        value: 'true'

    - name: Add GPG Program
      git_config:
        name: gpg.program
        scope: global
        state: present
        value: gpg              