version: '3.4'
services:
  awx-deploy:
    user: vscode    
    image: awx-deploy
    hostname: awx-deploy
    container_name: awx-deploy
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ..
    ports:
      - 22:22
    volumes:
      - ../.:/app
    networks:
      - devnet
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - ~/.psmware/psmware.env
volumes: 
  app: 

networks:
  devnet:
    external: true